# Generated by Django 3.1.7 on 2021-02-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdtenantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenantawaremodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdtenantapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sdtenantapp.tenantawaremodel')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('sdtenantapp.tenantawaremodel',),
        ),
    ]
